# Generated by Django 6.1 on 2026-08-18 18:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometry field representing the survey area, stored as a PostGIS polygon.', srid=4326)),
                ('area', models.FloatField(editable=False, help_text='Area in hectares, computed from the polygon on every save.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='workspace.workspace')),
            ],
        ),
    ]
